# Generated by Django 3.2.7 on 2021-10-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
